// <auto-generated />
namespace SC2Balance.Ingest.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostProcessingOutput : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostProcessingOutput));
        
        string IMigrationMetadata.Id
        {
            get { return "201312280047510_PostProcessingOutput"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
